# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- dev

resources:
- repo: self


variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and Push ApiGateway Image
      inputs:
        containerRegistry: $(DockerRegistry)
        repository: $(ApiGatewayRepository)
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/ApiGateway/Dockerfile'
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Build and Push IdentityService Image
      inputs:
        containerRegistry: $(DockerRegistry)
        repository: $(IdentityServiceRepository)
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/IdentityService/Dockerfile'
        tags: |
          $(tag)

    - task: Docker@2
      displayName: Build and Push UserService Image
      inputs:
        containerRegistry: $(DockerRegistry)
        repository: $(UserServiceRepository)
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/UserService/Dockerfile'
        tags: |
          $(tag)
